// Code generated by protoc-gen-go. DO NOT EDIT.
// source: currentLoop.proto

package cdh

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CurrentLoopRequest struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Timestamp            string   `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Value                int32    `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	Voltage              float32  `protobuf:"fixed32,4,opt,name=voltage,proto3" json:"voltage,omitempty"`
	Current              float32  `protobuf:"fixed32,5,opt,name=current,proto3" json:"current,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CurrentLoopRequest) Reset()         { *m = CurrentLoopRequest{} }
func (m *CurrentLoopRequest) String() string { return proto.CompactTextString(m) }
func (*CurrentLoopRequest) ProtoMessage()    {}
func (*CurrentLoopRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e231705269d59a9, []int{0}
}

func (m *CurrentLoopRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CurrentLoopRequest.Unmarshal(m, b)
}
func (m *CurrentLoopRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CurrentLoopRequest.Marshal(b, m, deterministic)
}
func (m *CurrentLoopRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CurrentLoopRequest.Merge(m, src)
}
func (m *CurrentLoopRequest) XXX_Size() int {
	return xxx_messageInfo_CurrentLoopRequest.Size(m)
}
func (m *CurrentLoopRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CurrentLoopRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CurrentLoopRequest proto.InternalMessageInfo

func (m *CurrentLoopRequest) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *CurrentLoopRequest) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *CurrentLoopRequest) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *CurrentLoopRequest) GetVoltage() float32 {
	if m != nil {
		return m.Voltage
	}
	return 0
}

func (m *CurrentLoopRequest) GetCurrent() float32 {
	if m != nil {
		return m.Current
	}
	return 0
}

type CurrentLoopResponse struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CurrentLoopResponse) Reset()         { *m = CurrentLoopResponse{} }
func (m *CurrentLoopResponse) String() string { return proto.CompactTextString(m) }
func (*CurrentLoopResponse) ProtoMessage()    {}
func (*CurrentLoopResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e231705269d59a9, []int{1}
}

func (m *CurrentLoopResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CurrentLoopResponse.Unmarshal(m, b)
}
func (m *CurrentLoopResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CurrentLoopResponse.Marshal(b, m, deterministic)
}
func (m *CurrentLoopResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CurrentLoopResponse.Merge(m, src)
}
func (m *CurrentLoopResponse) XXX_Size() int {
	return xxx_messageInfo_CurrentLoopResponse.Size(m)
}
func (m *CurrentLoopResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CurrentLoopResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CurrentLoopResponse proto.InternalMessageInfo

func (m *CurrentLoopResponse) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func init() {
	proto.RegisterType((*CurrentLoopRequest)(nil), "cdh.CurrentLoopRequest")
	proto.RegisterType((*CurrentLoopResponse)(nil), "cdh.CurrentLoopResponse")
}

func init() {
	proto.RegisterFile("currentLoop.proto", fileDescriptor_1e231705269d59a9)
}

var fileDescriptor_1e231705269d59a9 = []byte{
	// 219 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x3d, 0x4e, 0xc4, 0x30,
	0x10, 0x85, 0xf1, 0xee, 0x06, 0xb4, 0xb3, 0xda, 0x82, 0x01, 0x09, 0x0b, 0x51, 0x44, 0xa9, 0x42,
	0x93, 0x02, 0x6e, 0x00, 0x94, 0x54, 0x5e, 0x2e, 0x60, 0x92, 0x11, 0x46, 0x24, 0xb6, 0xb1, 0x27,
	0x41, 0xdc, 0x82, 0x23, 0xa3, 0xfc, 0xa0, 0x80, 0x42, 0xe7, 0xe7, 0xef, 0x49, 0xf3, 0xcd, 0xc0,
	0x69, 0xd9, 0x86, 0x40, 0x96, 0x1f, 0x9d, 0xf3, 0x85, 0x0f, 0x8e, 0x1d, 0xae, 0xcb, 0xca, 0x64,
	0x5f, 0x02, 0xf0, 0x7e, 0x46, 0x8a, 0xde, 0x5b, 0x8a, 0x8c, 0x08, 0x1b, 0xa3, 0xa3, 0x91, 0x22,
	0x15, 0xf9, 0x56, 0x0d, 0x6f, 0xbc, 0x82, 0x2d, 0xbf, 0x36, 0x14, 0x59, 0x37, 0x5e, 0xae, 0x06,
	0x30, 0x7f, 0xe0, 0x39, 0x24, 0x9d, 0xae, 0x5b, 0x92, 0xeb, 0x54, 0xe4, 0x89, 0x1a, 0x03, 0x4a,
	0x38, 0xe9, 0x5c, 0xcd, 0xfa, 0x85, 0xe4, 0x26, 0x15, 0xf9, 0x4a, 0xfd, 0xc4, 0x9e, 0x4c, 0x4a,
	0x32, 0x19, 0xc9, 0x14, 0xb3, 0x6b, 0x38, 0xfb, 0x63, 0x14, 0xbd, 0xb3, 0x91, 0xfe, 0x53, 0xba,
	0x39, 0xc0, 0xee, 0x57, 0x15, 0x1f, 0x60, 0x7f, 0x20, 0x5b, 0x3d, 0x51, 0x4d, 0x0d, 0x71, 0xf8,
	0xc4, 0x8b, 0xa2, 0xac, 0x4c, 0xb1, 0xdc, 0xef, 0x52, 0x2e, 0xc1, 0x38, 0x26, 0x3b, 0xba, 0xdb,
	0xc3, 0xce, 0x12, 0x7f, 0xb8, 0xf0, 0xd6, 0x97, 0x9e, 0x8f, 0x87, 0x6b, 0xdd, 0x7e, 0x07, 0x00,
	0x00, 0xff, 0xff, 0xaf, 0xeb, 0x6a, 0xed, 0x42, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CurrentLoopClient is the client API for CurrentLoop service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CurrentLoopClient interface {
	SendTelemetry(ctx context.Context, in *CurrentLoopRequest, opts ...grpc.CallOption) (*CurrentLoopResponse, error)
}

type currentLoopClient struct {
	cc grpc.ClientConnInterface
}

func NewCurrentLoopClient(cc grpc.ClientConnInterface) CurrentLoopClient {
	return &currentLoopClient{cc}
}

func (c *currentLoopClient) SendTelemetry(ctx context.Context, in *CurrentLoopRequest, opts ...grpc.CallOption) (*CurrentLoopResponse, error) {
	out := new(CurrentLoopResponse)
	err := c.cc.Invoke(ctx, "/cdh.CurrentLoop/SendTelemetry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CurrentLoopServer is the server API for CurrentLoop service.
type CurrentLoopServer interface {
	SendTelemetry(context.Context, *CurrentLoopRequest) (*CurrentLoopResponse, error)
}

// UnimplementedCurrentLoopServer can be embedded to have forward compatible implementations.
type UnimplementedCurrentLoopServer struct {
}

func (*UnimplementedCurrentLoopServer) SendTelemetry(ctx context.Context, req *CurrentLoopRequest) (*CurrentLoopResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendTelemetry not implemented")
}

func RegisterCurrentLoopServer(s *grpc.Server, srv CurrentLoopServer) {
	s.RegisterService(&_CurrentLoop_serviceDesc, srv)
}

func _CurrentLoop_SendTelemetry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CurrentLoopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrentLoopServer).SendTelemetry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cdh.CurrentLoop/SendTelemetry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrentLoopServer).SendTelemetry(ctx, req.(*CurrentLoopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CurrentLoop_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cdh.CurrentLoop",
	HandlerType: (*CurrentLoopServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendTelemetry",
			Handler:    _CurrentLoop_SendTelemetry_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "currentLoop.proto",
}
