name: proto

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      -
        name: Version
        id: Version
        run: |
          set -e
          export VERSION=$(jq '.version' < package.json | sed 's/"//g')
          echo "::set-env name=VERSION::$VERSION"
      -
        name: Install
        id: Install
        run: |
          npm install
      -
        name: Publish
        id: Publish
        run: |
          set -e
          echo $VERSION
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
